### ISSUE TITLE
Test and migrate to Angular 4

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#223]
http://angularjs.blogspot.de/2017/03/angular-400-now-available.html

**Comment by harunurhan** [comment]
For the update we can follow those things, then we'll see how many things will break, actually I suggest to wait 1-2 weeks so that our 3rd party dependencies will catch up with the new version 😄 

## Angular Update Guide - 2.3 -> 4.0 for Advanced Apps

### Before updating

- [ ] Ensure you don't use implements OnInit, or use implements with any lifecycle event. Instead use extends <lifecycle event>.
- [ ] Stop using deep imports, these symbols are now marked with ɵ and are not part of our public API.

### During the update

Update all of your dependencies to version 4 and the latest typescript.

- [ ]  If you are using Linux/Mac, you can use: `npm install @angular/{animations,common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router}@4.0.0 typescript@latest --save`

### After the update

- [ ] Rename your template tags to ng-template.
- [ ] Replace ngOutletContext with ngTemplateOutletContext.

**Comment by zzacharo** [comment]
@harunurhan where did you find the `Before Update ` requirements? I didn't find that changes...
