### ISSUE TITLE
Templating support for complex list item "View" mode

### ISSUE THREAD

**Issue by StellaCh** [inveniosoftware-contrib/ng2-json-editor#244]
Change the design of the list of references to appear as in pdf. If a link is broken, then show a 'warning' icon that suggests the user to edit. When clicked, then the individual fields of the reference will appear and the user will be able to add/remove fields in the reference

**Comment by harunurhan** [comment]
Since we do non content based features in this repo, I changed the name of the issue and the new description for this task is below, and I also created https://github.com/inspirehep/record-editor/issues/130.

- there should be a `itemTemplateName` config for `complex-list` fields.
- This template will be used as view template, and clicking on it will change to edit mode which is the default UI that we have now.

**Comment by harunurhan** [comment]
Fixed
