### ISSUE TITLE
Focus on the new list element when it is added

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#88]
When `+` button is clicked and new element added to a list field, cursor should focus to the first focusable `HTMLElement` in the new list element.

I don't know if that makes sense for every list but it definitely does for paginated or long lists.

@jmartinm ?

**Comment by jmartinm** [comment]
Yes, I agree that makes sense. The only thing we might lose with that is
the possibility of clicking multiple times the plus button on table list to
add, for example, three empty fields and then go to edit them.

On the other hand, instead of doing that, it will be more convenient using
a shortcut to add new fields below the one you are in, so focusing on the
newly added input still will be better than current behavior.

**Comment by harunurhan** [comment]
Fixed
