### ISSUE TITLE
Tree menu overflowed

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware-contrib/ng2-json-editor#91]
![screenshot from 2016-11-29 16-23-56](https://cloud.githubusercontent.com/assets/22594783/20715775/87a11be0-b650-11e6-9be9-395fb5d2909b.png)

**Comment by jmartinm** [comment]
@zzacharo can you add a description of what the problem is exactly?

**Comment by zzacharo** [comment]
The tooltips and dropdown menu of the left items are cuurently be hidden from the tree-menu colum. Probably the css of the tree-menu column has a z-index higher than the middle coumn and thus the popup elements are hidden below.

**Comment by jmartinm** [comment]
The same problem happened on the right side with the PDF panel. What I saw is that even if the `z-index` is correctly set the menus are still truncated.

The problem seems to be actually in the central div where the editor is. Since we have the scroll auto in the Y-axis this makes the content not show after the sides of the editor.

A workaround is to adjust the position of the messages and dropdowns on the left side so that they are positioned inside the editor.

**Comment by zzacharo** [comment]
oh i see..

**Comment by jmartinm** [comment]
The popover has been removed and the dropdowns are inside of the editor container, so this is not a problem any more.
